### ISSUE TITLE
Lines beginning with '**' break the resulting HTML

### ISSUE THREAD

**Issue by adamvleggett** [p01/mmd.js#7]
If I begin a line with bold text marked with a double *, the document gets a <ul><li></ul></li> and then no more output is generated, and existing tags are left unclosed. Additionally, bold text marked with a double underline is not supported.

A fix for both issues is to change inlineEscape() to look for `/__(.+)__/g` instead of stars, and add a line to replace double stars with double underlines.

It would also be handy if passing non-strings were handled elegantly.

Thanks for the great code.

**Comment by macfusion** [comment]
`.replace(/(\*\*|__)(?=\S)([^\r]*?\S[*_]*)\1/g, '<strong>$2</strong>')  // strong`
`.replace(/(\*|_)(?=\S)([^\r]*?\S)\1/g, '<em>$2</em>') // italic`

i think this way is not bad working with stars

**Comment by CarsonSlovoka** [comment]
> `.replace(/(\*\*|__)(?=\S)([^\r]*?\S[*_]*)\1/g, '\<strong\>$2\</strong\>') // strong`
>
>  `.replace(/(\*|_)(?=\S)([^\r]*?\S)\1/g, '\<em\>$2\</em\>') // italic`

I found that your solution has been adopted. Would you consider closing this question?

> https://github.com/p01/mmd.js/commit/338d8736b161b95b6529ca521612680d67839a0b#diff-6071e54f782d27c8dd57a0ad12040a7719f6428bc49467ccd3321592840b4c89R15-R16

**Comment by p01** [comment]
Thank you :)
