### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lxg** [p01/mmd.js#9]
I really love mmd.js, but the lack of a license makes it impossible to use them in public projects. Would you mind adding a license?

**Comment by p01** [comment]
Thanks!

Added the MIT license in 68a2a40
I'd love to hear how/where you used mmd.js

**Comment by lxg** [comment]
Great, thanks!

Regarding the usage, I'm integrating it into https://github.com/agitation/admin-bundle/ to add some basic formatting to error and UI messages.
